version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - db

  db:
    container_name: ecomm-db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${PGUSERNAME}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - PGDATA=${PGDATA}
    volumes:
      - ./data/db:/data/postgres
    ports:
      - "${PGPORT}:${PGPORT}"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ecomm_db"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge
